spring:
  profiles:
    active: dev

server:
  port: 8081
  servlet:
    context-path: /api-ms-security

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true

info:
  app:
    name: HIS - Microservicio de Seguridad
    description: API para autenticación, autorización y gestión de tokens
    version: 1.0.0